solid/solid-oidc

- index.bs
Bikeshed's Darkmode styles are sometimes completely unreadable and don't seem really accessible in their current state.
Therefore, I would advocate to disable it.
See also: https://github.com/tabatkins/bikeshed/issues/1806
> Disable darkmode

- .github/workflows/cd-config.yml
- .gitignore
This fixes the publication of generated assets to the `gh-pages` branch of the repository.
See in action:
- https://github.com/matthieubosquet/solid-oidc/actions/runs/1052036953
- https://github.com/matthieubosquet/solid-oidc/tree/gh-pages
Supersedes https://github.com/solid/solid-oidc/pull/7
> Amend GitHub pages publish

- index.bs
Clarify that:
1. Not all flows will rely upon a client secret
2. The Public OIDC client URI is not a WebID
> Clarify client registration

- README.md
This adds a reference to the Solid Code of Conduct in the Solid-OIDC README
> Add reference to the Solid Code of Conduct

- .github/workflows/cd-config.yml
- .github/workflows/ci-config.yml
- index.bs
- sequence.mmd
This PR will replace sequence diagram in the spec with one using more common format.
Currenly section in a spec has 8 bullet points, this diagram has 12. It splits 2 bi-directional arrows into separate req/res and adds req/res for getting user's WebID profile. If we agree on those changes I'll adjust bullet points in the spec and change from draft to PR.
> more common sequence diagram

- .github/workflows/cd-config.yml
The file pattern for SVG files is causing CD to fail. This should fix it.
> Adjust SVG file pattern for CD

- index.bs
Resolves #28
This removes the dependency on the draft WebID specification for Client ID Documents.
This has been discussed in the panel. At present, there is a conflict between the Solid-OIDC requirement for Client ID documents to be serialized as JSON-LD and the WebID draft specification requirement for Turtle.
> Rename Client WebID to Client Identifier

- index.bs
There is a new version of the DPoP draft published at https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-04
This updates the references to point to the new version.
> Update to latest DPoP draft specification

- primer/index.bs
Resolves #59 
As pointed out by @dschraudner, the primer was incorrectly describing the value of an `htm` claim
> Use the correct htm value in primer

- index.bs
- primer/index.bs
For Solid-OIDC servers implementing RP-initiated logout, the `post_logout_redirect_uris` property will need to be defined in the corresponding Solid vocabularies.
See also https://github.com/solid/vocab/pull/63
> Include post_logout_redirect_uris in JSON-LD context

- primer/index.bs
> remainging s/access token/id token/

- index.bs
Referring to the `ClientID` claim is confusing, especially since there used to be a `client_id` claim and OAuth 2.0 uses `client_id`. Instead, this changes the word "ClientID" to "authorized party" to align with the JWT claims being used.
> Refer to the azp rather than ClientId claim

- alternative-flows.md
This PR sets up a Markdown file detailing some use cases for authentication flows that do not fit in the OIDC Authorization Code Grant flow we currently depend upon within the Solid-OIDC specification. It also proposes three potential solutions we have already envisioned like using OAuth 2.0 Token Exchange with the OIDC IdP, expanding the UMA Authorization Service's supported profiles or introducing these specific flows into the specification. 
It is mainly intended to start a discussion on this topic.
- Issue #75 
- Discussion in the panel meeting of February 14, 2022.
> Alternative Authentication Flows

- .github/dependabot.yml
This will help us keep any GH action dependencies up-to-date
> Add dependabot for GH action version management

- primer/index.bs
This adds the Authorization Server entity to the primer. This also renames "Data Pod" to "Storage", in line with the Solid Protocol.
Related to #83
> Primer: Add Authorization server to actor list

- index.bs
- primer/index.bs
By including version numbers in the DPoP draft spec labels, we have to keep chasing these updates. Without the versions, we just need to ensure that the sections continue to align. Since some of us (I, at least) keep close track of the DPoP spec, this seems like an easier way to point implementors to the correct version
> Update to latest draft of DPoP

- index.bs
I moved ID Token verification into a section that is not specific to the AS.
I also reformulated OIDC Issuer Discovery so that it doesn't speak directly about verifying ID Token.
> make id token verification not be exclusive to AS

- index.bs
- primer/index.bs
There are three changes here, only one of which is significant.
The significant one changes the `SHOULD` to a `MUST` in the requirement for client identifier documents to use the normatively defined Solid-OIDC JSON-LD `@context`.
The rationale for this is simple: it makes for better interoperability.
If client identifier documents all use the same `@context`, then there will be less variation in how this data is serialized across the Solid ecosystem. Furthermore, other specifications that use particular context resources to structure JSON-LD data normatively require (`MUST`) the use of a defined context. For example:
* [W3C Verifiable Credentials](https://www.w3.org/TR/vc-data-model/#contexts)
* [W3C Web Annotations](https://www.w3.org/TR/annotation-model/#annotations)
* [IIIF …
> Require solid-oidc context in JSON-LD

- index.bs
This PR adds:
* #78 
* #95 
* #92 
* #91 
* #26 
* #47
> added issues inline for FPWD

- index.bs
- primer/index.bs
This changes the status of the Solid-OIDC draft specification from 'Editors Draft' to 'Community Group Draft'.
This is roughly equivalent to a "First Public Working Draft", as the panel prepares for a "~Candidate Recommendation" status
> Change status to 'Community Group Draft'

- .github/workflows/tr-draft-config.yml
- .github/workflows/tr-final-config.yml
- index.bs
- primer/index.bs
This improves the workflow for preparing the Solid-OIDC documents for publication in solidproject.org/TR by operating on the bikeshed document directly rather than replacing URLs in the produced HTML.
This also makes more effective use of the bikeshed metadata ordering mechanism
> Improve the TR draft workflow

- index.bs
- primer/index.bs
Resolves #98 
Depends on https://github.com/solid/specification/pull/386
Once the `CG-DRAFT` version is accepted into the protocol spec, this version will go back to being an editor's draft.
> Set editor's draft as ED status

- index.bs
- primer/index.bs
Resolves #104
The spec mostly uses Solid-OIDC, so I took that to be canonical (which is also my understanding).
> Use consistent naming for Solid-OIDC

- index.bs
Describe that global access tokens are outside the scope of this specification.
Resolves #117
> Rework the "Out of Scope" section

- index.bs
This provides more context for the use of Scope values when requesting information as claims
Resolves #127
> Clarify use of scope values

- index.bs
Resolves #120 
The text "in any case" was leading to confusion. It appears that the intended formulation of that text is "in either case".
Alternatively, we could remove most of the first paragraph, if it is not helpful.
> Clarify core concept text

- index.bs
closes #168
while https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
doesn't mention `scope`, it can be found in
https://datatracker.ietf.org/doc/html/rfc7591#section-4.1.2
should we change the normative reference?
> make webid scope required for DCR

- index.bs
After bikeshed failed to build in #190 with:
> FATAL ERROR: Obsolete biblio ref: [rfc7235] is replaced by [rfc9110]. Either update the reference, or use [rfc7235 obsolete] if this is an intentionally-obsolete reference.
> updated RFC7235 to RFC9110

- index.bs
- primer/index.bs
The examples in the docs are misleading and make people think the azp should be a WebID rather than a client ID.
> Change instances of webid for an client_id in examples to client_id 

- index.bs
As an alternative to #217 , I have moved the test suite to the `solid-contrib` organization. As such, this adjusts the URL for the test suite.
> Adjust test suite URL to point to solid-contrib repository

- index.bs
- primer/index.bs
The bikeshed tooling in CI is complaining about an unnecessary slash in an img tag.
> Fix CI/CD workflow

- index.bs
PR updates the SotD section given that the [Solid CG Charter](https://www.w3.org/community/solid/charter/) supersedes Solid Process.
> Remove mention of Solid Process from SotD

- primer/index.bs
- primer/primer-request.mmd
As discussed with @elf-pavlik, some fixes and improvements in the Primer:
- Steps 7 and 12 of the Request flow diagram was refering to access token instead of ID token.
- Show the kid in the ID Token at step 19 of the Authorization code PKCE flow.
- Add a reference to RFC7515 section 4.1.4 in step 12 of the Request flow.
See https://github.com/solid/solid-oidc/issues/229.
> Fix Primer token references and details
