- .github/workflows/cd-config.yml
- .github/workflows/ci-config.yml
- .gitignore
- setup.sh
Apologies @acoburn about this second commit, I hoped to submit before the previous merge, but you were faster!
PS: please squash for merging, this should be only one commit.
> Slight adjustments to the CI scripts

- index.bs
- primer/index.bs
Fixes the URL part of issue https://github.com/solid/solid-oidc/issues/11.
> Update specs URL

- index.bs
Update status of the document following the model in https://solidproject.org/TR/protocol#sotd.
Fixes the document status part of issue https://github.com/solid/solid-oidc/issues/11.
> Update document status

- README.md
This adds a simple README file to the repository to make it easier for interested parties to find what they are looking for.
> Add README file to repository

- index.bs
- primer/index.bs
per my action from last week meeting 
to ignore whitespace changes see: https://github.com/solid/solid-oidc/pull/45/files?diff=unified&w=1
> primer: updated sections mentioning Client ID Document

- index.bs
This adds a link to the test suite for Solid-OIDC
> Add link to test suite

- index.bs
I'm opening it as a draft to coordinate TODO during today's call.
> Reorganize spec

- index.bs
This is part of #65 
It also partially addresses #51 by removing the notion of implicit trust.
> created WebID Document section

- primer/index.bs
- primer/primer-login.mmd
This clarifies a number of errors and inconsistencies in the Solid OIDC Flow (section 4 of the primer) 
Related to #83
> Primer: Solid OIDC Flow

- primer/index.bs
- primer/logo.include
> primer: adjusted boilerplate

- index.bs
- primer/index.bs
> Add MIT license to spec and primer

- index.bs
- primer/index.bs
> Add created/modified metadata fields

- index.bs
> Adjust text and links in the JSON-LD section

- index.bs
> Link to unversioned JSON-LD spec

- primer/index.bs
> primer: use correct token in request flow (steps 7 & 8)

- index.bs
closes #197 
date based on 3190498add531755f842e2f4d4a7f9bf6ebccd10
> update created date

- primer/index.bs
This is a follow-up to https://github.com/solid/specification/pull/365.
> Remove obsolete inconsistent data pod reference

- primer/index.bs
Pedantic, sorry, but it caught my eye
> minor spelling correction persistant -> persistent

- primer/index.bs
> fixed some wording

- README.md
Action following multiple cases of uncertainty (cf. [matrix](https://matrix.to/#/!rUzJAFxzsTfTWEIQfp:gitter.im/$xEtmuBLbL7tVWIDI8gKVM1wh3u-LLlJIzLsJPOB674g?via=gitter.im&via=matrix.org&via=t2bot.io))
> fix: remove mention of meeting frequency

- .github/workflows/cd-config.yml
- .github/workflows/ci-config.yml
- .github/workflows/tr-draft-config.yml
- .github/workflows/tr-final-config.yml
- index.bs
- primer/index.bs
- setup.sh
https://github.com/speced/bikeshed-boilerplate/pull/83
previews:
* https://elf-pavlik.github.io/solid-oidc/
* https://elf-pavlik.github.io/solid-oidc/primer/
> use copyright and sotd from bikeshed-boilerplate
